version: "3.9"

services:
  bin:
    build: .docker/golang
    container_name: golang_web
    volumes:
      - ./:/go/src/app

  db:
    build: .docker/postgress/
    container_name: golang_postgress
    environment:
      POSTGRES_USER: goweb
      POSTGRES_PASSWORD: goweb
    volumes:
      - .docker/postgress/tmp:/var/lib/postgresql/data
    ports:
      - "9001:5432"
    networks:
      - goweb

networks:
  goweb: